In [13]:
# univariate lstm example
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [14]:
# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]

In [16]:
# choose a number of time steps
n_steps=3

In [17]:
# preprating dependent and independent features
def prepare_data(timeseries_data,n_steps):
    X, y=[],[]
    for i in range(len(timeseries_data)):
        end=i+n_steps
        if end>len(timeseries_data)-1:
            break
        seq_x=timeseries_data[i:end]
        seq_y=timeseries_data[end]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [18]:

# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [19]:
print(X),print(y)


[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [20]:
X.shape


(6, 3)

In [21]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [24]:

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 34854.2148
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 34040.4414
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 33389.4180
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32956.4570
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32572.2344
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 32128.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31553.9473
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30790.6406
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 29833.6465
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 28735.1309
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27329.2734
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25771.5078
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 24901.2012
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 24392.3828
Epoch 15/500
1/1 ━━━━━━━━━━━━━━

## Predicting For the next 10 data

In [28]:
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[223.62366]
1 day input [196.         210.         223.62365723]
1 day output [[232.10527]]
2 day input [210.         223.62365723 232.10527039]
2 day output [[246.08942]]
3 day input [223.62366 232.10527 246.08942]
3 day output [[258.82495]]
4 day input [232.10527 246.08942 258.82495]
4 day output [[269.01337]]
5 day input [246.08942 258.82495 269.01337]
5 day output [[283.09207]]
6 day input [258.82495 269.01337 283.09207]
6 day output [[296.0886]]
7 day input [269.01337 283.09207 296.0886 ]
7 day output [[308.43903]]
8 day input [283.09207 296.0886  308.43903]
8 day output [[323.11328]]
9 day input [296.0886  308.43903 323.11328]
9 day output [[337.31888]]
[223.62366, 232.10527, 246.08942, 258.82495, 269.01337, 283.09207, 296.0886, 308.43903, 323.11328, 337.31888]


In [29]:
lst_output

[223.62366,
 232.10527,
 246.08942,
 258.82495,
 269.01337,
 283.09207,
 296.0886,
 308.43903,
 323.11328,
 337.31888]